Traceback (most recent call last):
  File "C:\Users\edier\miniconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\edier\miniconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edier\AppData\Roaming\Python\Python311\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edier\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\edier\miniconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\edier\miniconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\edier\miniconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
# Set up figure and axis
f, ax = plt.subplots(1, figsize=(12, 9))
# Generate and add hexbin with 50 hexagons in each dimension, no borderlines, half transparency, and the reverse viridis colormap
hb = ax.hexbin(
    db['x'], 
    db['y'],
    gridsize=50, 
    linewidths=0,
    alpha=0.5, 
    cmap='viridis_r'
)
# Add basemap
ctx.add_basemap(
    ax, 
    source=ctx.providers.CartoDB.Positron
)
# Add colorbar
plt.colorbar(hb)
# Remove axes
ax.set_axis_off()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[9], line 14[0m
[0;32m      5[0m hb [38;5;241m=[39m ax[38;5;241m.[39mhexbin(
[0;32m      6[0m     db[[38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m], 
[0;32m      7[0m     db[[38;5;124m'[39m[38;5;124my[39m[38;5;124m'[39m],
[1;32m   (...)[0m
[0;32m     11[0m     cmap[38;5;241m=[39m[38;5;124m'[39m[38;5;124mviridis_r[39m[38;5;124m'[39m
[0;32m     12[0m )
[0;32m     13[0m [38;5;66;03m# Add basemap[39;00m
[1;32m---> 14[0m [43mctx[49m[38;5;241m.[39madd_basemap(
[0;32m     15[0m     ax, 
[0;32m     16[0m     source[38;5;241m=[39mctx[38;5;241m.[39mproviders[38;5;241m.[39mCartoDB[38;5;241m.[39mPositron
[0;32m     17[0m )
[0;32m     18[0m [38;5;66;03m# Add colorbar[39;00m
[0;32m     19[0m plt[38;5;241m.[39mcolorbar(hb)

[1;31mNameError[0m: name 'ctx' is not defined

